USE bd_rv;

INSERT INTO brand
VALUES
	(1, 'Toyota'),
    (2, 'Volkswagen'),
    (3, 'Honda'),
    (4, 'Hyundai'),
    (5, 'Kia'),
    (6, 'Ford'),
    (7, 'Chevrolet'),
    (8, 'Tesla'),
    (9, 'Jeep'),
    (10, 'BMW'),
    (11, 'Mercedes-Benz'),
    (12, 'Audi'),
    (13, 'Lexus'),
    (14, 'BYD'),
    (15, 'MG'),
    (16, 'Xiaomi'),
    (17, 'Peugeot'),
    (18, 'Renault'),
    (19, 'Citroën'),
    (20, 'Mazda'),
    (21, 'Subaru'),
    (22, 'Mitsubishi'),
    (23, 'Nissan'),
    (24, 'Fiat'),
    (25, 'SEAT'),
    (26, 'Cupra'),
    (27, 'Alfa Romeo'),
    (28, 'Changan'),
    (29, 'Geely'),
    (30, 'GWM'),
    (31, 'Chery'),
    (32, 'Omoda'),
    (33, 'Porsche'),
    (34, 'Ferrari'),
    (35, 'McLaren'),
    (36, 'Lamborghini'),
    (37, 'Aston Martin');
    
INSERT INTO model
VALUES
	(1, 'Agya'),
    (2, 'Wigo'),
    (3, 'Yaris'),
    (4, 'Corolla'),
    (5, 'Camry'),
    (6, 'Prius'),
    (7, 'Crown'),
    (8, 'Raize'),
    (9, 'Yaris Cross'),
    (10, 'Corolla Cross'),
    (11, 'RAV4'),
    (12, '4Runner'),
    (13, 'Highlander'),
    (14, 'Grand Highlander'),
    (15, 'Prado'),
    (16, 'Sequoia'),
    (17, 'bZ4X'),
    (18, 'Hilux'),
    (19, 'Tacoma'),
    (20, 'Tundra'),
    (21, 'GR86'),
    (22, 'GR Supra'),
    (23, 'GR Yaris'),
    (24, 'GR Corolla'),
    (25, 'Sienna'),
    (26, 'Hiace'),
    (27, 'Model Y'),
    (28, 'F-150'),
    (29, 'Tucson'),
    (30, 'Sportage'),
    (31, 'Kicks'),
    (32, 'Tiguan'),
    (33, 'Versa'),
    (34, 'K3'),
    (35, 'Swift'),
    (36, 'Jetta'),
    (37, 'Civic'),
    (38, 'Qashqai'),
    (39, 'Seltos'),
    (40, 'CX-30'),
    (41, 'Stepway'),
    (42, 'MG ZS'),
    (43, 'Sandero'),
    (44, 'Clio');